# Generated by Django 4.2.19 on 2025-02-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LandingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LaunchSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_module', models.CharField(max_length=255)),
                ('lunar_module', models.CharField(max_length=255)),
                ('crew', models.ManyToManyField(to='api.crewmember')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('launch_date', models.DateField()),
                ('landing_date', models.DateField()),
                ('landing_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landingsite')),
                ('launch_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.launchsite')),
                ('spacecraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spacecraft')),
            ],
        ),
    ]
