# Generated by Django 4.2.19 on 2025-02-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_crewmember_landingsite_launchsite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='landing_site',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='launch_site',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='spacecraft',
        ),
        migrations.RemoveField(
            model_name='spacecraft',
            name='crew',
        ),
        migrations.DeleteModel(
            name='CrewMember',
        ),
        migrations.DeleteModel(
            name='LandingSite',
        ),
        migrations.DeleteModel(
            name='LaunchSite',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Spacecraft',
        ),
    ]
