# Generated by Django 4.2.19 on 2025-02-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_mission_landing_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LaunchSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lunarmission',
            name='crew',
        ),
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_module', models.CharField(max_length=100)),
                ('lunar_module', models.CharField(max_length=100)),
                ('crew', models.ManyToManyField(to='api.crewmember')),
            ],
        ),
        migrations.AddField(
            model_name='lunarmission',
            name='landing_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.landingsite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunarmission',
            name='spacecraft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.spacecraft'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lunarmission',
            name='launch_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.launchsite'),
        ),
    ]
